cnstll/ft_transcendAnce

frontend/app/.eslintrc.js
frontend/app/package-lock.json
frontend/app/package.json
frontend/app/yarn.lock

Disable eslint auto-install in front

---

backend/app/src/auth/auth.service.ts

53 bug mismatch between code and db schema

---

backend/app/package.json
backend/app/prisma/seed.ts
package.json

adding seeding script, just run 'npm run prisma:db:seed

---

backend/app/src/user/dto/friend.dto.ts
backend/app/src/user/user.controller.ts
backend/app/src/user/user.service.ts
backend/app/test/app.e2e-spec.ts

77 us create endpoint to get user info including user friends

---

backend/app/src/auth/auth.controller.ts
backend/app/src/main.ts
frontend/app/src/components/global-components/interface.tsx
frontend/app/src/components/global-components/profile.tsx
frontend/app/src/components/section-components/friend-list.tsx
frontend/app/src/components/section-components/users-list-item.tsx
frontend/app/src/components/section-components/users-list.tsx

83 us linking friends list to the back end

---

frontend/app/package-lock.json
frontend/app/package.json
frontend/app/src/components/customed-hooks/useUserFriends.tsx
frontend/app/src/components/global-components/profile.tsx
frontend/app/src/components/section-components/friend-list.tsx
package-lock.json
package.json

replaced plain axios request with a react Query hook

---

backend/app/src/user/user.controller.ts
backend/app/src/user/user.service.ts

add logout function

---

docker-compose.yaml

fix console errors by adding env variable to docker compose

---

backend/app/src/pong/entities/game.entities.ts

21 us as a player i want to win the game when i hit 10 points

---

backend/app/src/auth/auth.service.ts
backend/app/src/user/user.controller.ts
backend/app/src/user/user.service.ts

fixed get target data endpoint and clarified naming one findOne methods

---

backend/app/src/user/user.controller.ts
backend/app/src/user/user.service.ts

added endpoints to get leaderboard + user ranking

---

frontend/app/src/components/section-components/chat/create-channel-form.tsx

Regex check for inputs in channel creation form

---

backend/app/src/pong/game.service.ts

fixes issue with the disconnecting player winning the game

---

backend/app/src/pong/dto/position.dto.ts
backend/app/src/pong/entities/game.entities.ts
backend/app/src/pong/game.gateway.ts
backend/app/src/pong/game.service.ts
frontend/app/src/components/section-components/play/canvas.tsx

145 bug leaving a game when in the waiting room causes issues in the backend

---

.github/ISSUE_TEMPLATE/bug.yml

Removing required env fields

---

backend/app/src/pong/entities/game.entities.ts
backend/app/src/pong/game.gateway.ts
backend/app/src/pong/game.service.ts
frontend/app/src/components/global-components/play.tsx
frontend/app/src/components/section-components/play/canvas.tsx

119 us as a user i want to have a polished experience with the game

---

frontend/app/src/components/section-components/chat/channels-list.tsx

The shortest commit in my all life

---

frontend/app/src/components/section-components/chat/display-messages.tsx

Text now wrapped in chat bubble

---

backend/app/src/channel/dto/index.ts
frontend/app/src/components/section-components/search-box-channel.tsx

Change tailwind css to have the search bar location depending of the size of the screen

fix(search bar): fix channel search bar

---

frontend/app/src/components/section-components/users-list-item.tsx

Removing ban component from friends options

---

backend/app/src/auth/auth.service.ts
backend/app/src/auth/dto/auth.dto.ts

fix getting the avatar from the modified 42 api

---

frontend/app/src/components/section-components/one-box.tsx

You can now scroll over the user in the ranking

fix(ranking): ranking box now overflows

---

backend/app/src/channel/channel.gateway.ts
backend/app/src/channel/channel.service.ts

no delete password needed now (origin of the bug)

fixed connect to use the userOnChannel relation instead of channel

---

backend/app/src/pong/entities/game.entities.ts
backend/app/src/pong/game.service.ts
frontend/app/src/components/section-components/play/canvas.tsx

Ending messages at the end of a game are displayed according to the game result for each user

fix(game): fix ending message

---

frontend/app/src/components/global-components/chat.tsx

 Chat automatically scroll down to last sent message 

---

backend/app/prisma/migrations/20221124104532_channel_action/migration.sql
backend/app/prisma/schema.prisma

Added ban array
Added block array
Added time value for mute and ban
Delete requesterId since the requester already keeps track of the banned or muted user

feat(db):  change database for mute, ban and block

---

frontend/app/src/components/global-components/navbar.tsx
frontend/app/src/components/section-components/search-box-user.tsx

156 bug can access yourself in search bar

---

frontend/app/src/components/section-components/chat/channel-options.tsx

249 bug on leaving channel channel is not removed from channel list

---

frontend/app/src/components/section-components/chat/password-modal.tsx

fix error wording in password modal

---

frontend/app/src/components/section-components/chat/channel-options.tsx

(backend was already refusing invite requests for other channel's type)

fix only display invite modal for private channel 

---

frontend/app/src/components/section-components/game/canvas.tsx

A comprehensive first attempt at improving the game's user experience on mobile devices

---

frontend/app/src/components/global-components/chat.tsx
frontend/app/src/components/section-components/chat/channel-header.tsx
frontend/app/src/components/section-components/chat/search-channel-item.tsx
frontend/app/src/components/section-components/drop-down-button.tsx
frontend/app/src/components/section-components/search-box-channel.tsx
frontend/app/src/components/section-components/search-box-user.tsx
frontend/app/src/components/section-components/search-user-item.tsx
frontend/app/src/components/section-components/users-list-item.tsx
frontend/app/src/components/section-components/users-list.tsx

266 bug fix channel banner and issue on modals and search box

---

frontend/app/src/components/section-components/profile/nickname-form.tsx

Added feedback on user editing his/her nickname 👍 
1- feedback while typing (too long or characters not accepted)
2- feedback when submitting (too long, chars not accepted or already taken)
3- change the design to align with the beautiful 2FA modal

276 bug add feedback in change username

---

frontend/app/src/components/global-components/chat.tsx
frontend/app/src/components/section-components/chat/display-messages.tsx

Fix image of current user not displayed instantly by passing the avatar image in props

fix(message): display image current user instantly

---

frontend/app/src/components/global-components/chat.tsx
frontend/app/src/components/section-components/chat/channel-options.tsx
frontend/app/src/components/section-components/chat/chat-top-bar.tsx
frontend/app/src/components/section-components/chat/invite-modal.tsx

- Can now invite user in private chan
- Bonus fix: when name is edited, new name is displayed in top bar of message box

invitation for private messages fixed

---

frontend/app/src/components/global-components/ranking.tsx
frontend/app/src/components/section-components/friend-status.tsx

added loader on ranking + friendship requests and update

---

frontend/app/src/components/section-components/chat/chat-top-bar.tsx
frontend/app/src/components/section-components/profile/upload-picture.tsx

Changed the upload button to a smaller, without border image uploader because it was too big on mobile (it was going out of the modal)
Added margin on the channel's name on mobile because it was too close to the border

small design fixes

---

frontend/app/src/components/global-components/chat.tsx
frontend/app/src/components/query-hooks/getModerationActionInfo.tsx
frontend/app/src/components/query-hooks/useGetChannelUsers.tsx
frontend/app/src/components/query-hooks/useGetChannels.tsx
frontend/app/src/components/query-hooks/useIsCurrentUserUnderModerationInChannel.tsx
frontend/app/src/components/query-hooks/useIsUserUnderModerationInChannel.tsx
frontend/app/src/components/section-components/users-list-item.tsx

- Query fetching is activated / deactivated based on pathname 

Queries related to an active channel are now dependant on it existing

---

frontend/app/src/components/section-components/users-list-item.tsx

Remove result of query to display status

fix(friends): friends status in profile

---

backend/app/prisma/seed.ts

Change seed so you can edit les demons de minuit + hidden chat group so that it respects the lenght

fix(seed): change seed so you can edit channel

---

backend/app/src/pong/game.service.ts

Add status pending to delete the game

fix(game): fix by Colomban add status pending

---

backend/app/src/channel/channel.service.ts

fix(channel): on edit if no password is provided error displayed

---

frontend/app/src/components/global-components/navbar.tsx

No more console log error by setting option draggable to false

fix(invite): set draggable to false

---

backend/app/src/auth/auth.controller.ts
backend/app/src/channel/channel.service.ts
backend/app/src/user/user.service.ts
frontend/app/src/App.tsx
frontend/app/src/components/global-components/home.tsx
frontend/app/src/components/global-components/routing-public-private.tsx
frontend/app/src/components/query-hooks/useCheckIsLoggedIn.tsx

- Adding protected / public route 
- redirecting to sign-in if on protected route with no valid cookie

263 bug console error on user info on the homepage

---

backend/app/src/2fa/two.factor.authentication.controller.ts
frontend/app/src/components/global-components/home.tsx
frontend/app/src/components/global-components/routing-public-private.tsx

adding a check on data from userInfo hook

---

backend/app/src/user/user.controller.ts
frontend/app/src/components/section-components/profile/upload-picture.tsx

Toast error if image is too big
Check file extension in back

fix(upload a picture): add max size + check file extension in back

---

frontend/app/src/App.tsx

removing protected root around 2FA

---

backend/app/src/pong/game.gateway.ts
backend/app/src/pong/game.service.ts
frontend/app/src/components/global-components/navbar.tsx
frontend/app/src/components/section-components/game/canvas.tsx

some game invite cleanup and minor fixes

---

backend/app/src/user/user.controller.ts

Fix by checking if file exists

336 bug 500 upload picture
